apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - image: eclipse-mosquitto:1.6.7
        imagePullPolicy: Always
        name: mosquitto
        ports:
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: ws
          containerPort: 9001
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/data
          name: mosquitto-data
        - mountPath: /mosquitto/config
          name: mosquitto-config
        - mountPath: /mosquitto/passwd
          name: mosquitto-passwd
      volumes:
      - name: mosquitto-data
        persistentVolumeClaim:
          claimName: mosquitto-data-local-path
      - name: mosquitto-passwd
        secret:
          secretName: mosquitto-passwd
      - name: mosquitto-config
        configMap:
            name: mosquitto-config