apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-local-path
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi