apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: LoadBalancer
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
    protocol: TCP
  - name: ws
    port: 9001
    targetPort: 9001
    protocol: TCP
  selector:
    app: mosquitto